swagger:
  enable: true   # 正式环境中关闭swagger的使用
#mybatis:
  #Mapper.xml所在的位置
#  mapper-locations: classpath:mapper/*.xml
  #entity扫描的包名
#  type-aliases-package: com.kdkj.dc.entity
#  configuration:
 #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
#    cache-enabled: true
spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
  # 使用德鲁伊
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://192.168.20.8:3306/caijin?allowMultiQueries=true
    username: root
     # 下面为连接池的补充设置，应用到上面所有数据源中
     # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    spring.datasource.filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
#  cache:
#    type: redis
#    ehcache:
#      config: classpath:ehcache.xml
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    #password:
#    password: root
#    timeout: 50
#    jedis:
#      pool:
#       # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 3600
#        # 连接池中的最小空闲连接
#        min-idle: 0
  jackson:
    # 全局jackson配置
    default-property-inclusion: non_null
  application:
    name: caijin
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  resources:
    static-locations: classpath:/resources/,classpath:/static/,file:${web.multipart-path}
web:
  multipart-path: ./src/main/resources/static/files/

thread:
  #核心数
  core-pool-size: 10
  #最大线程池数
  max-pool-size: 50
  #队列容量
  queue-capacity: 10
  #日志
logging:
  config: classpath:logback-spring.xml
server:
  port: 8088
  servlet:
    context-path: /